# Generated by Django 2.1.4 on 2018-12-27 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peoples', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(choices=[('TI', 'TI'), ('DD', 'Design'), ('EVALUATION', 'Evaluation'), ('SECRATARY', 'Secreatary')], default='TI', max_length=20),
        ),
    ]
