# Generated by Django 2.1.4 on 2018-12-27 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peoples', '0002_auto_20181227_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
